name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-26.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: 
          github.com:443
          metrics.semgrep.dev:443
          semgrep.dev:443
        
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - uses: returntocorp/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
